$(function(){
    $('.close-btn').click(function(){
        $('#popup').fadeOut(200);
    });
    $('.gnb-btn').click(function(){
        $('.gnb').fadeIn(300);
    });
    $('.btn-close').click(function(){
        $('.gnb').fadeOut(300);
    });
});
